name: Planen
favicon: null
layout_spectrum: 0.4750670597422868
typography_spectrum: 0.8312058537267148
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5041679886635393
  lightness: 0.8506629345938563
  saturation: 0.29152946546673775
  rhythmicContrast: 0.1668992021586746
purpose: []
